name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          baseUrlPath: https://omelhordeviajar.com.br/  
          pathToRoot: .
          sitemapFormat: xml
          includeHTML: true
          includePDF: false

      - name: Commit & Push Sitemap
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Atualiza sitemap.xml" || echo "Nada para commit"
          git push