name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Botão manual

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para histórico completo

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@2.0.0
        with:
          base-url: https://omelhordeviajar.com.br
          path-to-root: .
          sitemap-format: xml
          include-html: true

      - name: Commit & Push Sitemap
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Atualiza sitemap.xml (auto)" || echo "Nada para commit"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main